server:
  port: 8602
  servlet:
    context-path: /dev
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/data

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml